/*To Deal with accounts data*/

var mongoose = require('mongoose');

var oneTimeInvoiceItemDetails = new mongoose.Schema({
    id: {type: Number},
    item: {type: String, trim: true},
    description: {type: String, trim: true},
    unit_price: {type: String, trim: true},
    qty: {type: Number, trim: true}
});

var accountsSchema = new mongoose.Schema({
    invoice_no: {type: String, trim: true}, // reference to invoice collection define type of user
    amount: {type: String, trim: true},
    dueDate: {type: Date, default: Date.now},
    created: {type: Date, default: Date.now},
    auto_pay: {type: String, trim: true},
    ack_saas: {type: Boolean, default: false},
    paid_buyer: {type: Boolean, default: false},
    paid_seller: {type: Boolean, default: false},
    owedToID: {type: mongoose.Schema.ObjectId, ref: 'User'},//Account Recievable - Invoice generated From
    pay_fromID: {type: mongoose.Schema.ObjectId, ref: 'User'},//Account Payable - Invoice generated To
    callHistoriesID: {type: mongoose.Schema.ObjectId, ref: 'User'},
    item: {type: String, trim: true}, // this is category name of offer
    description: {type: String, trim: true}, // this is offer title of campaign
    owedTo: {type: String, trim: true}, //name of owedTo
    userType: {type: String, trim: true},//user role of owedTo - Account Recievable
    pay_from: {type: String, trim: true},//name of payFrom
    payerType: {type: String, trim: true},//user role of payFrom - Account Payable
    payment_status: {type: Boolean, default: false},
    payment_mode: {type: String, trim: true},
    saas_commission: {type: Number, trim: true, default: 0},
    oneTimeInvoiceDetails: {
        multipleItemList: [oneTimeInvoiceItemDetails],
        fromDetails: {
            name: {type: String},
            address: {type: String},
            location: {type: String},
            country: {type: String}
        },
        toDetails: {
            name: {type: String},
            address: {type: String},
            location: {type: String},
            country: {type: String}
        },
        notes: {type: String, trim: true},
        guestUserEmail: {type: String}
    },
    invoiceType: {type: String, default: 'autogenerated'}, //autogenerated OR onetime
    guestUser: {type: Boolean, default: false}
})
module.exports = mongoose.model('Account', accountsSchema);